---

# file: tasks/compile-protobuf.yml

# - name: PROTOBUF | clean build dir
#   file:
#     state: absent
#     path: "{{ protobuf_build }}"

- name: PROTOBUF | check if install exists
  stat:
    path: "{{ protobuf_install_dir }}"
  register: protobuf_exists

- name: PROTOBUF | Get sources
  become: true
  get_url: url={{ protobuf_url }} dest={{ protobuf_tmp }} timeout=180 force=no
  when: not protobuf_exists.stat.exists
  register: protobuf_downloaded

- name: PROTOBUF | Extract sources
  become: true
  unarchive: src={{ protobuf_tmp }}
             dest="/tmp"
             creates={{ protobuf_build }}
             remote_src=yes
  when: protobuf_downloaded.changed
  register: protobuf_sources

- name: PROTOBUF | Make build folder
  become: true
  file: path={{ protobuf_build_dir }} state=directory
  when: protobuf_downloaded.changed

- name: PROTOBUF | run cmake
  command:  chdir="{{ protobuf_build_dir }}" \
            cmake -G "Unix Makefiles" {{ protobuf_build }}/cmake \
            -DCMAKE_C_COMPILER={{ gcc_install_dir }}/bin/gcc \
            -DCMAKE_CXX_COMPILER={{ gcc_install_dir }}/bin/g++ \
            -DGCC_INSTALL_PREFIX={{ gcc_install_dir }} \
            -DCMAKE_CXX_LINK_FLAGS="-L{{ gcc_install_dir }}/lib64 -Wl,-rpath,{{ gcc_install_dir }}/lib64" \
            -DCMAKE_INSTALL_RPATH="{{ gcc_install_dir }}/lib64" \
            -DCMAKE_INSTALL_PREFIX={{ protobuf_install_dir }} \
            -DCMAKE_BUILD_TYPE="Release" \
            {{ protobuf_build }}/cmake
  when: protobuf_sources.changed
  register: protobuf_cmake

- name: PROTOBUF | Make
  become: true
  shell: chdir={{ protobuf_build_dir }} make
  when: protobuf_cmake.changed
  register: protobuf_make

- name: PROTOBUF | Install
  become: true
  shell: chdir={{ protobuf_build_dir }} make install
  when: protobuf_make.changed
  register: protobuf_install

- name: PROTOBUF | cleanup build
  become: true
  file:
    path: "{{ protobuf_build_dir }}"
    state: absent
  when: protobuf_install.changed

- name: PROTOBUF | cleanup tmp
  become: true
  file:
    path: "{{ protobuf_tmp }}"
    state: absent
  when: protobuf_install.changed


...
